53/add rental history
AdamVig/stockpile-api pull request #121
Opened 2017-03-05 14:20 UTC by AdamVig

Closes #53.

2017-03-05 21:19 UTC, emroussel requested changes
Does this PR add both rental history and item filtering by rental?

2017-03-05 21:19 UTC, emmanuelroussel commented on README.md
> +The values of the query parameters ending in `ID` are the IDs of the entities they specify in the database. They value of the `available` parameter is a boolean (`0` or `1`) representing whether the
You have a typo here. `They value` should be `The value`.

2017-03-06 13:03 UTC, AdamVig commented
Yes, it does add both. We originally thought that I would be adding filtering by date, etc to the rental API, but as I was building it, we decided to skip that for now. So I implemented filtering by rental status instead.

2017-03-06 16:49 UTC, emroussel approved these changes

2017-03-06 16:49 UTC, merged