14/add organization authentication
AdamVig/stockpile-api pull request #55
Opened 2017-02-14 20:31 UTC by AdamVig

Closes #14.

This PR will cause test coverage to decline. #54 addresses test coverage for this feature.

2017-02-14 21:02 UTC, emroussel requested changes
Can you add a section in the README describing how to add the authentication header to requests (mostly for the format)?

2017-02-14 21:02 UTC, emmanuelroussel commented on controllers/auth.js
> +  if (req.body.name && req.body.email && req.body.password) {
Should there be a check after this to make sure the email is not already used and send an appropriate error message if it is the case?

2017-02-14 22:31 UTC, AdamVig commented on controllers/auth.js
> +  if (req.body.name && req.body.email && req.body.password) {
Good point. I think I might add a unique constraint to the email column in the database, ensuring that an error will be returned if an email is non-unique. What do you think?

2017-02-14 22:41 UTC, emmanuelroussel commented on controllers/auth.js
> +  if (req.body.name && req.body.email && req.body.password) {
Yeah good idea. Would that return the appropriate error code from the api though? (I think it should be a 409)

2017-02-15 04:50 UTC, AdamVig commented on controllers/auth.js
> +  if (req.body.name && req.body.email && req.body.password) {
Good point! I'll catch the error from the database and return the appropriate error code.

2017-02-15 04:54 UTC, AdamVig commented on controllers/auth.js
> +  if (req.body.name && req.body.email && req.body.password) {
Just want to point out that this functionality already exists, so I won't actually have to add a commit to this PR in order for it to work (I outsmarted myself): [see db.js](https://github.com/AdamVig/stockpile-api/blob/master/services/db.js#L26). 😃

2017-02-15 15:16 UTC, emroussel approved these changes

2017-02-16 15:34 UTC, merged